// Experimental build-time generator. No generated code or registration is shipped
// by Houdini. The benchmark feeds this the same selections as its query artifacts.
export function recordShapes(selections) {
	const shapes = new Map()
	const visited = new Set()
	function visit(selection) {
		if (!selection || visited.has(selection)) return
		visited.add(selection)
		for (const fields of [selection.fields, ...Object.values(selection.abstractFields?.fields ?? {})]) {
			if (!fields) continue
			const names = Object.keys(fields).filter(name => fields[name].visible)
			if (names.length) shapes.set(JSON.stringify(names), names)
			for (const field of Object.values(fields)) visit(field.selection)
		}
	}
	selections.forEach(visit)
	return [...shapes.values()]
}

export function generateRecords(shapes) {
	const classes = shapes.map((names, index) => {
		const name = `Record${index}`
		return `
class ${name} extends PlainRecord {
${names.map((_, i) => `#raw${i}; #value${i};`).join('\n')}
constructor(read) {
super();
${names.map((field, i) => `this.#raw${i} = read(${JSON.stringify(field)}); this.#value${i} = $state.raw(this.#raw${i});`).join('\n')}
Object.defineProperties(this, descriptors${index});
Object.freeze(this);
}
${names.map((field, i) => `get [${JSON.stringify(field)}]() { return this.#value${i}; }`).join('\n')}
static peek(record, field) {
switch (field) {
${names.map((field, i) => `case ${JSON.stringify(field)}: return record.#raw${i};`).join('\n')}
}
}
static write(record, field, value) {
switch (field) {
${names.map((field, i) => `case ${JSON.stringify(field)}: record.#raw${i} = value; record.#value${i} = value; return;`).join('\n')}
default: throw new Error('Unknown generated record field: ' + field);
}
}
static matches(names) { return names.length === ${names.length} && ${names.map((field, i) => `names[${i}] === ${JSON.stringify(field)}`).join(' && ')}; }
}
const descriptors${index} = Object.fromEntries(${JSON.stringify(names)}.map(name => [name, {
get: Object.getOwnPropertyDescriptor(${name}.prototype, name).get,
set: reject, enumerable: true, configurable: false,
}]));
`
	}).join('\n')
	return `// Generated by perf/svelte-dashboard/generated-records/generate.mjs.
import { getRecordMetadata } from 'houdini/runtime/cache/identity';
// Returning a plain object from the base constructor lets the derived class put
// private rune fields on it while preserving ordinary result-object prototypes.
class PlainRecord { constructor() { return {}; } }
const reject = () => { throw new TypeError('Reactive results are readonly. Use a mutation or cache.write() to update data.'); };
${classes}
const layouts = [${shapes.map((_, i) => `Record${i}`).join(',')}];
const selected = new WeakMap();
export const generatedRecords = new WeakMap();
export function createGeneratedRecord(snapshot, names, read) {
const fields = getRecordMetadata(snapshot)?.fields;
let layout = fields && selected.get(fields);
if (!layout?.matches(names)) {
layout = layouts.find(candidate => candidate.matches(names));
if (!layout) return undefined;
if (fields) selected.set(fields, layout);
}
const record = new layout(read);
generatedRecords.set(record, layout);
return record;
}
`
}
